# Generated by Django 4.0.6 on 2023-07-19 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FB', 'Facebook'), ('LI', 'LinkedIn'), ('IG', 'Instagram'), ('TW', 'Twitter'), ('GH', 'GitHub')], max_length=5)),
                ('url', models.URLField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.profile')),
            ],
            options={
                'unique_together': {('profile', 'name')},
            },
        ),
    ]
